### ISSUE TITLE
[Bug]: [Security] [Sealed Secrets] Catalog secret have only 2 var not 4

### ISSUE THREAD

**Issue by allamand** [aws-samples/eks-workshop-v2#332]
### What happened?

in the workshop : 

```
kubectl -n catalog get deployment catalog -o yaml | yq '.spec.template.spec.containers[] | .env'
- name: DB_USER
  valueFrom:
    secretKeyRef:
      key: username
      name: catalog-db
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: catalog-db
- name: DB_NAME
  valueFrom:
    configMapKeyRef:
      key: name
      name: catalog
- name: DB_READ_ENDPOINT
  valueFrom:
    secretKeyRef:
      key: endpoint
      name: catalog-db
- name: DB_ENDPOINT
  valueFrom:
    secretKeyRef:
      key: endpoint
      name: catalog-db

```

and in reality:
```
- name: DB_USER
  valueFrom:
    secretKeyRef:
      key: username
      name: catalog-db
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: catalog-db
```

### What did you expect to happen?

so some commands whil failed like : 

kubectl -n catalog get secrets catalog-db --template {{.data.endpoint}} | base64 -d
catalog-mysql:3306%                                                                                                                                                                                             
~
$
kubectl -n catalog get secrets catalog-db --template {{.data.name}} | base64 -d
catalog%  

as it don't exists

### How can we reproduce it?

just deploy the catalog service

### EKSversion

1.23
