### ISSUE TITLE
[Bug]: Crossplane rds intial password step missing from instructions

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#532]
### Installation method

Own AWS account

### What happened?

When doing the managed and composition lab for Crossplane the step to set the initial password of the rds database is missing.

cc @niallthomson 

### What did you expect to happen?

For the step to present to create the secret:
```
    masterUserPasswordSecretRef:
      key: password
      name: catalog-db-crossplane
      namespace: catalog
```
Or explain to the user how the initial password is created if automated by crossplane provider when no present.

### How can we reproduce it?

Run thru the latest version of the lab

### EKS version

default 1.23
