### ISSUE TITLE
[Bug]: [Security] [Sealed Secrets] Catalog secret have only 2 var not 4

### ISSUE THREAD

**Issue by syvanen** [aws-samples/eks-workshop-v2#556]
### Installation method

Workshop Studio

### What happened?

Following bug has reappeared in live version of workshop: https://github.com/aws-samples/eks-workshop-v2/issues/332
https://www.eksworkshop.com/docs/security/sealed-secrets/exploring-secrets#exploring-the-catalog-pod

The page lists 4 ENV variables but there are only 2 in the live environment.

So when issuing this command `kubectl -n catalog get deployment catalog -o yaml | yq '.spec.template.spec.containers[] | .env'` output was:

```
- name: DB_USER
  valueFrom:
    secretKeyRef:
      key: username
      name: catalog-db
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: catalog-db
```

### What did you expect to happen?

Get 4 variables like document says. Looking at the configuration files there should be only 2, so documentation needs to be corrected.

Copy command
```
~
$
kubectl -n catalog get deployment catalog -o yaml | yq '.spec.template.spec.containers[] | .env'
- name: DB_USER
  valueFrom:
    secretKeyRef:
      key: username
      name: catalog-db
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: catalog-db
- name: DB_NAME
  valueFrom:
    configMapKeyRef:
      key: name
      name: catalog
- name: DB_READ_ENDPOINT
  valueFrom:
    secretKeyRef:
      key: endpoint
      name: catalog-db
- name: DB_ENDPOINT
  valueFrom:
    secretKeyRef:
      key: endpoint
      name: catalog-db
```

### How can we reproduce it?

Run the workshop in Workshop Studio and look into `/workspace/manifests/catalog/deployment.yaml`. It contains:
```
        - name: catalog
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: password
          envFrom:
            - configMapRef:
                name: catalog
```

### EKS version

1.23
